{% set version = "bfcb9f9" %}

package:
  name: fgr
  version: {{ version }}

source:
  git_url: https://github.com/intel-isl/FastGlobalRegistration.git
  git_tag: {{ version }}
  patches:

build:
  number: {{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
  run:

test:
  commands:
  files:

about:
  home: https://github.com/intel-isl/FastGlobalRegistration
  license: MIT
  summary: Fast Global Registration
  description:

extra:
  recipe-maintainers:
