{% set version = "isis7" %} # synched up to isis dependencies for this version

package:
  name: fgr
  version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/FastGlobalRegistration.git
# git_tag: {{ version }} # if commented out will use the latest version
  patches:

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - flann                     1.9.1
    - eigen                     3.4.0

  run:
    - flann                     1.9.1
    - eigen                     3.4.0

test:
  commands:
  files:

about:
  home: https://github.com/intel-isl/FastGlobalRegistration
  license: MIT
  summary: Fast Global Registration
  description:

extra:
  recipe-maintainers:
