{% set version = "e78ce15" %}

package:
  name: fgr
  version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/FastGlobalRegistration.git
  git_tag: {{ version }}
  patches:

build:
  number: {{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - flann                     1.9.1
    - eigen                     3.3.7
  run:
    - flann                     1.9.1
    - eigen                     3.3.7

test:
  commands:
  files:

about:
  home: https://github.com/intel-isl/FastGlobalRegistration
  license: MIT
  summary: Fast Global Registration
  description:

extra:
  recipe-maintainers:
