{% set version = "asp3.5.0" %} # synched up to isis dependencies for this version

package:
  name: fgr
  version: {{ version }}

source:
  git_url: git@github.com:NeoGeographyToolkit/FastGlobalRegistration.git
# git_tag: {{ version }} # if commented out will use the latest version
  patches:

build:
  number: 1

requirements:
  build:
    - cmake                     3.27.9
  host:
    # Having compilers as part of dependencies as in the local env helps
    # sort out issues with conda-build and ISIS compatibility.
    - c-compiler                1.9.0
    - compilers                 1.9.0
    - cxx-compiler              1.9.0
    - fortran-compiler          1.9.0
    - flann                     1.9.1
    - eigen                     3.4.0

  run:
    - flann                     1.9.1
    - eigen                     3.4.0

test:
  commands:
  files:

about:
  home: https://github.com/intel-isl/FastGlobalRegistration
  license: MIT
  summary: Fast Global Registration
  description:

extra:
  recipe-maintainers:
